const CITIES = Object.freeze({
    'ARI': 'Arizona',
    'ATL': 'Atlanta',
    'BAL': 'Baltimore',
    'BUF': 'Buffalo',
    'CAR': 'Carolina',
    'CHI': 'Chicago',
    'CIN': 'Cincinnati',
    'CLE': 'Cleveland',
    'DAL': 'Dallas',
    'DEN': 'Denver',
    'DET': 'Detroit',
    'GB': 'Green Bay',
    'HOU': 'Houston',
    'IND': 'Indianapolis',
    'JAX': 'Jacksonville',
    'KC': 'Kansas City',
    'LAC': 'Los Angeles',
    'LAR': 'Los Angeles',
    'MIA': 'Miami',
    'MIN': 'Minnesota',
    'NE': 'New England',
    'NO': 'New Orleans',
    'NYG': 'New York',
    'NYJ': 'New York',
    'OAK': 'Oakland',
    'PHI': 'Philadelphia',
    'PIT': 'Pittsburgh',
    'SF': 'San Francisco',
    'SEA': 'Seattle',
    'TB': 'Tampa Bay',
    'TEN': 'Tennessee',
    'WAS': 'Washington',
});
module.exports = CITIES;